package models;

public enum Action {
    REGISTER,
    LOGIN,
    LOGOUT,
    UPDATE_CREDENTIALS,
    MAKE_PROPOSAL,
    REQUEST_GAME_STATUS,
    REQUEST_GAME_STATS,
    REQUEST_LEADERBOARD,
    REQUEST_PERSONAL_STATS
}
